# Generated by Django 3.2.3 on 2021-06-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Date',
            new_name='date_created',
        ),
    ]
