# Generated by Django 3.2.3 on 2021-06-26 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dilike',
            field=models.ManyToManyField(related_name='dislike_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
