# Generated by Django 3.2.3 on 2021-06-26 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0006_post_dilike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dilike',
        ),
        migrations.AddField(
            model_name='post',
            name='dilikes',
            field=models.ManyToManyField(related_name='dislike_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
