# Generated by Django 3.2.3 on 2021-06-26 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_auto_20210626_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dilikes',
            new_name='dislikes',
        ),
    ]
