# Generated by Django 3.2.3 on 2021-06-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(default='Click the above link to read the post', max_length=500),
        ),
    ]
